# Etapa de restauración
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS restore
WORKDIR /src

# Copiar el archivo de proyecto y solución y restaurar dependencias
COPY EstadoCuenta_FrontEnd/*.csproj EstadoCuenta_FrontEnd/
COPY EstadoCuenta_FrontEnd/*.sln EstadoCuenta_FrontEnd/
RUN dotnet restore EstadoCuenta_FrontEnd/EstadoCuenta_FrontEnd.csproj

# Etapa de construcción
FROM restore AS build


# Copiar el resto de los archivos y compilar la aplicación
COPY EstadoCuenta_FrontEnd/ EstadoCuenta_FrontEnd/
RUN dotnet publish EstadoCuenta_FrontEnd/EstadoCuenta_FrontEnd.csproj -c Release -o /app

# Etapa de ejecución
FROM mcr.microsoft.com/dotnet/aspnet:6.0 
WORKDIR /app

# Exponer los puertos necesarios
EXPOSE 80
EXPOSE 5140

# Copiar la salida de la etapa de construcción a la etapa de ejecución
COPY --from=build /app .

# Punto de entrada para la aplicación
ENTRYPOINT ["dotnet", "EstadoCuenta_FrontEnd.dll"]