# Etapa de restauración
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS restore
WORKDIR /src

# Copiar el archivo de proyecto y solución y restaurar dependencias
COPY EstadoCuenta_Backend/*.csproj EstadoCuenta_Backend/
COPY EstadoCuenta_Backend/*.sln EstadoCuenta_Backend/
RUN dotnet restore EstadoCuenta_Backend/EstadoCuenta_Backend.csproj

# Etapa de construcción
FROM restore AS build

# Copiar el resto de los archivos y compilar la aplicación
COPY EstadoCuenta_Backend/ EstadoCuenta_Backend/
RUN dotnet publish EstadoCuenta_Backend/EstadoCuenta_Backend.csproj -c Release -o /app

# Etapa de ejecución
FROM mcr.microsoft.com/dotnet/aspnet:6.0 
WORKDIR /app

# Exponer los puertos necesarios
EXPOSE 80
EXPOSE 5141

# Copiar la salida de la etapa de construcción a la etapa de ejecución
COPY --from=build /app .

# Punto de entrada para la aplicación
ENTRYPOINT ["dotnet", "EstadoCuenta_Backend.dll"]